behaviors:
  MLAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      batch_size: 256
      buffer_size: 500000
      buffer_init_steps: 1000
      tau: 0.005
      steps_per_update: 15
      init_entcoef: 0.5
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 10000
engine_settings:
  width: 84
  height: 84
  quality_level: 2
  time_scale: 2
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
